// my_functions.h
#ifndef SYSCALLS_H
#define SYSCALLS_H

#include <sys/types.h>
#include <sys/time.h>
#include <sys/resource.h>
#include <sys/sysinfo.h>
#include <sys/times.h>
#include <sys/ptrace.h>
#include <unistd.h>
#include <syslog.h>
#include <signal.h>
#include <linux/capability.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <sys/wait.h>
#include <sys/sem.h>
#include <sys/shm.h>
#include <sys/msg.h>
#include <fcntl.h>
#include <sys/file.h>
#include <sys/utsname.h>
#include <sys/select.h>
#include <sys/mman.h>
#include <dirent.h>
#include <poll.h>
#include <sys/ioctl.h>
#include <arpa/inet.h>
#include <sys/stat.h>
#include <sys/xattr.h>
#include <time.h>
#include <sys/statfs.h>
#include <sys/syscall.h>
#include <sys/prctl.h>
#include <linux/fs.h>
#include <linux/utsname.h>
#include <sys/io.h>
#include <sys/sched.h>
#include <sys/param.h>
#include <stdio.h>
#include <stdlib.h>

// Function declarations

void template_kill();
void template_getpid();
void template_setdomainname();
void template_iopl();
void template_ioperm();
void template_init_module();
void template_delete_module();
void template_quotactl();
void template_gettid();
void template_readahead();
void template_setxattr();
void template_lsetxattr();
void template_fsetxattr();
void template_getxattr();
void template_lgetxattr();
void template_fgetxattr();
void template_listxattr();
void template_llistxattr();
void template_flistxattr();
void template_removexattr();
void template_lremovexattr();
void template_fremovexattr();
void template_tkill();
void template_time();
void template_futex();
void template_sched_setaffinity();
void template_sched_getaffinity();
void template_io_setup();
void template_io_destroy();
void template_io_getevents();
void template_io_submit();
void template_io_cancel();
void template_sigaltstack();
void template_utime();
void template_mknod();
void template_personality();
void template_ustat();
void template_statfs();
void template_fstatfs();
void template_sysfs();
void template_getpriority();
void template_setpriority();
void template_sched_setparam();
void template_sched_getparam();
void template_sched_setscheduler();
void template_sched_getscheduler();
void template_sched_get_priority_max();
void template_sched_get_priority_min();
void template_sched_rr_get_interval();
void template_mlock();
void template_munlock();
void template_mlockall();
void template_munlockall();
void template_vhangup();
void template_modify_ldt();
void template_pivot_root();
void template_prctl();
void template_arch_prctl();
void template_adjtimex();
void template_setrlimit();
void template_chroot();
void template_sync();
void template_acct();
void template_settimeofday();
void template_mount();
void template_umount();
void template_swapon();
void template_swapoff();
void template_reboot();
void template_sethostname();
void template_getsockname();
void template_getpeername();
void template_socketpair();
void template_setsockopt();
void template_getsockopt();
void template_clone();
void template_fork();
void template_vfork();
void template_execve();
void template_exit();
void template_wait4();
void template_newuname();
void template_semget();
void template_semop();
void template_semctl();
void template_shmdt();
void template_msgget();
void template_msgsnd();
void template_msgrcv();
void template_msgctl();
void template_fcntl();
void template_flock();
void template_fsync();
void template_fdatasync();
void template_truncate();
void template_ftruncate();
void template_getdents();
void template_getcwd();
void template_chdir();
void template_fchdir();
void template_rename();
void template_mkdir();
void template_rmdir();
void template_creat();
void template_link();
void template_unlink();
void template_symlink();
void template_readlink();
void template_chmod();
void template_fchmod();
void template_chown();
void template_fchown();
void template_lchown();
void template_umask();
void template_gettimeofday();
void template_access();
void template_pipe();
void template_select();
void template_sched_yield();
void template_mremap();
void template_msync();
void template_mincore();
void template_madvise();
void template_shmget();
void template_shmat();
void template_shmctl();
void template_dup();
void template_dup2();
void template_pause();
void template_nanosleep();
void template_getitimer();
void template_alarm();
void template_setitimer();
void template_sendfile64();
void template_accept();
void template_sendto();
void template_recvfrom();
void template_sendmsg();
void template_recvmsg();
void template_shutdown();
void template_bind();
void template_listen();
void template_newstat();
void template_newfstat();
void template_newlstat();
void template_poll();
void template_lseek();
void template_mprotect();
void template_brk();
void template_rt_sigaction();
void template_rt_sigprocmask();
void template_rt_sigreturn();
void template_pread64();
void template_pwrite64();
void template_readv();
void template_writev();
void template_read();
void template_write();
void template_open();
void template_close();
void template_mmap();
void template_munmap();
void template_ioctl();
void template_socket();
void template_connect();
void template_getrlimit();
void template_getrusage();
void template_sysinfo();
void template_times();
void template_ptrace();
void template_getuid();
void template_syslog();
void template_getgid();
void template_setuid();
void template_setgid();
void template_geteuid();
void template_getegid();
void template_setpgid();
void template_getppid();
void template_getpgrp();
void template_setsid();
void template_setreuid();
void template_setregid();
void template_getgroups();
void template_setgroups();
void template_setresuid();
void template_getresuid();
void template_setresgid();
void template_getresgid();
void template_getpgid();
void template_setfsuid();
void template_setfsgid();
void template_getsid();
void template_capget();
void template_capset();
void template_rt_sigpending();
void template_rt_sigtimedwait();
void template_rt_sigqueueinfo();
void template_rt_sigsuspend();

#endif // SYSCALLS_H
